---
title: "VPB"
author: "Alexey Luchinsky"
date: "12/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
```


```{r}
library(Rcpp)
library(rbenchmark)
library(dplyr)
```

```{r}
source("./VPB.R")
```



```{r}
X <- circle2d + rnorm(200,mean = 0,sd = 0.1) # add Gaussian noise  
# compute PD using Rips filtration
D <- calculate_homology(X,dim = 1,threshold = 2) 
# switch from birth-death to birth-persistence coordinates
D[,3] <- D[,3] - D[,2] 
colnames(D)[3] <- "persistence"
```


```{r}
# compute VPB for homological dimension H0 and tau=0.5
xSeq <- unique(quantile(D[D[,1]==1,2],probs = seq(0,1,by=0.1)))
ySeq <- unique(quantile(D[D[,1]==0,3],probs = seq(0,1,by=0.1))) 
T0 <- VPB(D,dimension = 0,xSeq,ySeq,tau = 0.5)
sourceCpp("VPB_cpp.cpp")
T0_C <- VPB_C(D,dimension = 0, xSeq, ySeq, 0.5)
all.equal(T0, T0_C)
```


```{r}
sourceCpp("VPB_cpp.cpp")
# compute VPB for homological dimension H1 and tau=0.5
xSeq <- unique(quantile(D[D[,1]==1,2],probs = seq(0,1,by=0.1)))
ySeq <- unique(quantile(D[D[,1]==1,3],probs = seq(0,1,by=0.1)))
T1 <- VPB(D,dimension = 1,xSeq,ySeq,tau = 0.5) 
T1_C <- VPB_C(D,dimension = 1, xSeq, ySeq, 0.5)
all.equal(T1, T1_C)
```

```{r}
nD <- 1e3
DList <-  list()
for(i in 1:nD) {
  X <- circle2d + rnorm(200,mean = 0,sd = 0.1)
  D <- calculate_homology(X,dim = 1,threshold = 2)
  D[,3] <- D[,3] - D[,2] 
  colnames(D)[3] <- "persistence"
  DList[[i]] <- D
}
```


```{r}
# calculates VPB on diagram D using function func
calc_VPB <- function(func = VPB, D = DList[[sample(1:length(DList),1)]], dimension = 0, tau = runif(1)) {
  xSeq <- unique(quantile(D[D[,1]==1,2],probs = seq(0,1,by=0.1)))
  ySeq <- unique(quantile(D[D[,1]==1,3],probs = seq(0,1,by=0.1)))
  func(D, dimension, xSeq, ySeq, tau)
}
# compares the VPBs generated by methods fun1, fun2 using given dimension, tau
compare_fun <- function(fun1 = VPB, fun2 = VPB_C, dimension = 0, tau = runif(1), n=1e2) {
  all(replicate(n, {
  D <- DList[[sample(1:length(DList),1)]]
  all.equal(
    calc_VPB(func = fun1, D = D, dimension = dimension, tau = tau),
    calc_VPB(func = fun2, D = D, dimension = dimension, tau = tau)
  )
  }))
}
# compares time of  VPBs generation by methods fun1, fun2 using given dimension, tau
compare_time <- function(fun1 = VPB, fun2 = VPB_C, dimension = 0, tau = runif(1), n=1e3) {
  rbenchmark::benchmark(
    R = calc_VPB( fun1,   dimension = dimension),
    C = calc_VPB( fun2, dimension = dimension),
    replications = n
    ,columns = c("test", "relative")
  ) %>% arrange(relative) %>% mutate(dimension = dimension)
}
```

```{r}
compare_fun(dimension = 0)
compare_fun(dimension = 1)
```

```{r}
compare_time(dimension = 0)
compare_time(dimension = 1)
```


